package pro.sketchware.creator.runtime;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Privacy-safe diagnostic event generated by Creator Runtime. */
public final class CreatorRuntimeEvent {
    public enum Severity { DEBUG, INFO, WARNING, ERROR }

    private final long timestampEpochMs;
    private final String projectId;
    private final long revision;
    private final String category;
    private final String name;
    private final Severity severity;
    private final String correlationId;
    private final Map<String, Object> attributes;

    public CreatorRuntimeEvent(long timestampEpochMs, String projectId, long revision,
                               String category, String name, Severity severity,
                               String correlationId, Map<String, Object> attributes) {
        this.timestampEpochMs = timestampEpochMs;
        this.projectId = projectId;
        this.revision = revision;
        this.category = category;
        this.name = name;
        this.severity = severity;
        this.correlationId = correlationId;
        this.attributes = Collections.unmodifiableMap(new LinkedHashMap<>(attributes == null
                ? Collections.<String, Object>emptyMap() : attributes));
    }

    public long getTimestampEpochMs() { return timestampEpochMs; }
    public String getProjectId() { return projectId; }
    public long getRevision() { return revision; }
    public String getCategory() { return category; }
    public String getName() { return name; }
    public Severity getSeverity() { return severity; }
    public String getCorrelationId() { return correlationId; }
    public Map<String, Object> getAttributes() { return attributes; }
}
